.TH JUBE-AUTORUN "1" "December 2015" "jube 2.1.0" "User Commands"
.SH NAME
jube-autorun \- Automatically run a set of JUBE benchmarks.
.SH DESCRIPTION
usage: jube-autorun
.SH AUTHORS
.B JUBE
was primarily written by Forschungszentrum Juelich GmbH, Juelich Supercomputing Centre
.SH "SEE ALSO"
Full documentation of
.B JUBE
is available at http://www.fz-juelich.de/ias/jsc/EN/Expertise/Support/Software/JUBE/JUBE2/jube-documentation_node.html
